name: Patch Revanced
on:
  workflow_dispatch:

jobs:
  read-config:
    name: Read Configuration
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.read-matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Read Matrix Config
        id: read-matrix
        uses: actions/github-script@main
        with:
          script: |
            const fs = require('fs');
            const path = './patch-config.json';
            const matrix = JSON.parse(fs.readFileSync(path, 'utf8')).patch_list;
            core.setOutput("matrix", JSON.stringify(matrix));

  patch-apps:
    name: Patch Applications
    needs: read-config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.read-config.outputs.matrix) }}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Patch Application
        env:
          APP_NAME: ${{ matrix.app_name }}
          SOURCE: ${{ matrix.source }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m src
